### ISSUE TITLE
Allow favorites.yml as alternative to favorites.txt

### ISSUE THREAD

**Issue by lunelson** [oleg-shilo/sublime-favorites#3]
This is an enhancement request, to allow a YAML format `favorites.yml` file as an alternative to `favorites.txt` so that one could have a list of objects with keys like `path` and `name`.

The use-case is when the favorite files all have the same base-name and are not differentiated in the Favorites list, e.g.:

```
path/to/project/aktuelles/index.pug
path/to/project/aktuelles/neuigkeiten/index.pug
path/to/project/aktuelles/termine/index.pug
path/to/project/aktuelles/neuigkeiten/neuigkeit-detail/index.pug
path/to/project/hwr/bereiche/fbx/index.pug
path/to/project/hwr/bereiche/index.pug
path/to/project/studium/angebote/studiengang-detail/index.pug
path/to/project/hwr/bereiche/fbx/personen/person-detail-max/index.pug
path/to/project/hwr/arbeiten/stellen/stelle-detail/index.pug
```
...which leads to a favorites list like this

```
index.pug
index.pug
index.pug
index.pug
index.pug
index.pug
index.pug
index.pug
index.pug
```
I would propose a YAML format like this:
```yml
-
  path: path/to/project/aktuelles/index.pug
  name: Aktuelles
-
  path: path/to/project/aktuelles/neuigkeiten/index.pug
  name: Neuigkeiten
-
  path: path/to/project/aktuelles/termine/index.pug
  name: Termine

[etc]
```
unless someone sees a better way of doing this?
